[nfs_clients]
nfs-client ansible_host=10.25.67.180 ansible_user=root

[nfs_clients:vars]
nfs_server_host=10.25.67.100
nfs_mounts='[{"export_path":"/home","mount_point":"/home"},{"export_path":"/hpcdata","mount_point":"/hpcdata"}]'
nfs_mount_options=rw,sync,hard,intr,vers=4
